import { z } from 'zod';

/**
 * Catálogo de Unidades de Medida para COVE y Facturas (México)
 * Incluye 1204 claves con su(s) descripción(es).
 * Generado automáticamente a partir del PDF oficial.
 */

// Enum de claves de unidad de medida
export const unidadDeMedidaEnum = z.enum(['05', '06', '08', '1A', '1B', '1C', '1D', '1E', '1F', '1G', '1H', '1I', '1J', '1K', '1L', '1M', '1X', '22', '23', '24', '25', '26', '27', '28', '29', '2A', '2B', '2C', '2I', '2J', '2K', '2L', '2M', '2N', '2P', '2Q', '2R', '2U', '2V', '2W', '2X', '2Y', '2Z', '30', '31', '32', '33', '34', '35', '36', '37', '38', '3B', '3C', '3E', '3G', '3H', '3I', '40', '41', '43', '44', '45', '46', '47', '48', '4A', '4B', '4C', '4E', '4G', '4H', '4K', '4L', '4M', '4N', '4O', '4P', '4Q', '4R', '4T', '4U', '4W', '4X', '53', '54', '56', '57', '58', '59', '5A', '5B', '5C', '5E', '5F', '5G', '5H', '5I', '5J', '5K', '5P', '5Q', '60', '61', '62', '63', '64', '66', '69', '71', '72', '73', '74', '76', '77', '78', '80', '81', '84', '85', '87', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'AA', 'AB', 'AD', 'AE', 'AH', 'AI', 'AJ', 'AK', 'AL', 'AM', 'AP', 'AQ', 'AR', 'AS', 'AV', 'AW', 'AY', 'AZ', 'B0', 'B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B9', 'BB', 'BD', 'BE', 'BG', 'BH', 'BJ', 'BK', 'BL', 'BO', 'BP', 'BR', 'BT', 'BW', 'BX', 'BZ', 'C0', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'CA', 'CG', 'CH', 'CJ', 'CK', 'CL', 'CO', 'CQ', 'CR', 'CS', 'CT', 'CU', 'CV', 'CY', 'CZ', 'D1', 'D2', 'D5', 'D6', 'D7', 'D8', 'D9', 'DB', 'DC', 'DD', 'DE', 'DG', 'DI', 'DJ', 'DN', 'DQ', 'DR', 'DS', 'DT', 'DU', 'DX', 'DY', 'E2', 'E3', 'E4', 'E5', 'EA', 'EB', 'EC', 'EP', 'EQ', 'EV', 'F1', 'F9', 'FB', 'FC', 'FD', 'FE', 'FF', 'FG', 'FH', 'FL', 'FM', 'FP', 'FR', 'FS', 'G2', 'G3', 'G7', 'GB', 'GC', 'GD', 'GE', 'GF', 'GH', 'GJ', 'GK', 'GL', 'GM', 'GN', 'GO', 'GP', 'GQ', 'GT', 'GV', 'GW', 'GY', 'GZ', 'H1', 'H2', 'HA', 'HC', 'HD', 'HE', 'HF', 'HH', 'HI', 'HJ', 'HK', 'HL', 'HM', 'HN', 'HO', 'HP', 'HS', 'HT', 'HY', 'IA', 'IC', 'IE', 'IF', 'II', 'IL', 'IM', 'IP', 'IT', 'IU', 'IV', 'J2', 'JB', 'JE', 'JG', 'JK', 'JM', 'JO', 'JR', 'K1', 'K2', 'K3', 'K5', 'K6', 'KA', 'KB', 'KD', 'KF', 'KG', 'KI', 'KJ', 'KL', 'KO', 'KR', 'KS', 'KT', 'KW', 'KX', 'L2', 'LA', 'LC', 'LD', 'LE', 'LF', 'LH', 'LI', 'LJ', 'LK', 'LM', 'LN', 'LO', 'LP', 'LR', 'LS', 'LX', 'LY', 'M1', 'M4', 'M5', 'M7', 'M9', 'MA', 'MC', 'MD', 'MF', 'MK', 'MO', 'MQ', 'MT', 'MV', 'N1', 'N2', 'N3', 'NA', 'NB', 'NC', 'ND', 'NE', 'NF', 'NG', 'NH', 'NI', 'NJ', 'NL', 'NN', 'NQ', 'NR', 'NT', 'NV', 'NX', 'NY', 'OA', 'ON', 'OP', 'OT', 'OZ', 'P0', 'P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8', 'P9', 'PA', 'PB', 'PD', 'PE', 'PF', 'PG', 'PI', 'PK', 'PM', 'PN', 'PO', 'PQ', 'PR', 'PS', 'PT', 'PU', 'PV', 'PW', 'PY', 'PZ', 'Q3', 'QA', 'QB', 'QD', 'QH', 'QK', 'QR', 'QT', 'R1', 'R4', 'R9', 'RA', 'RD', 'RG', 'RH', 'RK', 'RL', 'RM', 'RN', 'RO', 'RP', 'RS', 'RT', 'RU', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'SA', 'SD', 'SE', 'SG', 'SK', 'SL', 'SN', 'SO', 'SP', 'SQ', 'SR', 'SS', 'ST', 'SV', 'SW', 'SX', 'T0', 'T1', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'TA', 'TC', 'TD', 'TE', 'TF', 'TI', 'TJ', 'TK', 'TL', 'TN', 'TP', 'TQ', 'TR', 'TS', 'TT', 'TU', 'TV', 'TW', 'TY', 'U1', 'U2', 'UA', 'UB', 'UC', 'UD', 'UE', 'UF', 'UH', 'UM', 'UN', 'VA', 'VI', 'VQ', 'VS', 'W2', 'W4', 'WA', 'WB', 'WE', 'WG', 'WH', 'WI', 'WM', 'WW', 'X1', 'YL', 'YT', 'Z1', 'Z2', 'Z3', 'Z4', 'Z5', 'Z6', 'Z8', 'ZP', 'ZZ', 'A10', 'A11', 'A12', 'A13', 'A14', 'A15', 'A16', 'A17', 'A18', 'A19', 'A20', 'A21', 'A22', 'A23', 'A24', 'A25', 'A26', 'A27', 'A28', 'A29', 'A30', 'A31', 'A32', 'A33', 'A34', 'A35', 'A36', 'A37', 'A38', 'A39', 'A40', 'A41', 'A42', 'A43', 'A44', 'A45', 'A47', 'A48', 'A49', 'A50', 'A51', 'A52', 'A53', 'A54', 'A55', 'A56', 'A57', 'A58', 'A59', 'A60', 'A61', 'A62', 'A63', 'A64', 'A65', 'A66', 'A67', 'A68', 'A69', 'A70', 'A71', 'A73', 'A74', 'A75', 'A76', 'A77', 'A78', 'A79', 'A80', 'A81', 'A82', 'A83', 'A84', 'A85', 'A86', 'A87', 'A88', 'A89', 'A90', 'A91', 'A92', 'A93', 'A94', 'A95', 'A96', 'A97', 'A98', 'A99', 'ACR', 'ACT', 'AMH', 'AMP', 'ANN', 'APZ', 'ARE', 'ASM', 'ASU', 'ATM', 'ATT', 'B10', 'B11', 'B12', 'B13', 'B14', 'B15', 'B16', 'B17', 'B18', 'B19', 'B20', 'B21', 'B22', 'B23', 'B24', 'B25', 'B26', 'B27', 'B28', 'B29', 'B30', 'B31', 'B32', 'B33', 'B34', 'B35', 'B36', 'B37', 'B38', 'B39', 'B40', 'B41', 'B42', 'B43', 'B44', 'B45', 'B46', 'B47', 'B48', 'B49', 'B50', 'B51', 'B52', 'B53', 'B54', 'B55', 'B56', 'B57', 'B58', 'B59', 'B60', 'B61', 'B62', 'B63', 'B64', 'B65', 'B66', 'B67', 'B68', 'B69', 'B70', 'B71', 'B72', 'B73', 'B74', 'B75', 'B76', 'B77', 'B78', 'B79', 'B80', 'B81', 'B82', 'B83', 'B84', 'B85', 'B86', 'B87', 'B88', 'B89', 'B90', 'B91', 'B92', 'B93', 'B94', 'B95', 'B96', 'B97', 'B98', 'B99', 'BAR', 'BFT', 'BHP', 'BLD', 'BLL', 'BQL', 'BTU', 'BUA', 'BUI', 'C10', 'C11', 'C12', 'C13', 'C14', 'C15', 'C16', 'C17', 'C18', 'C19', 'C20', 'C21', 'C22', 'C23', 'C24', 'C25', 'C26', 'C27', 'C28', 'C29', 'C31', 'C32', 'C33', 'C34', 'C35', 'C36', 'C37', 'C38', 'C39', 'C40', 'C41', 'C42', 'C43', 'C44', 'C45', 'C46', 'C47', 'C48', 'C49', 'C50', 'C51', 'C52', 'C53', 'C54', 'C55', 'C56', 'C57', 'C58', 'C59', 'C60', 'C61', 'C62', 'C63', 'C64', 'C65', 'C66', 'C67', 'C68', 'C69', 'C70', 'C71', 'C72', 'C73', 'C74', 'C75', 'C76', 'C77', 'C78', 'C79', 'C80', 'C81', 'C82', 'C83', 'C84', 'C85', 'C86', 'C87', 'C88', 'C89', 'C90', 'C91', 'C92', 'C93', 'C94', 'C95', 'C96', 'C97', 'C98', 'C99', 'CCT', 'CDL', 'CEL', 'CEN', 'CGM', 'CKG', 'CLF', 'CLT', 'CMK', 'CMQ', 'CMT', 'CNP', 'CNT', 'COU', 'CTG', 'CTM', 'CTN', 'CUR', 'CWA', 'CWI', 'D03', 'D04', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'D32', 'D33', 'D34', 'D35', 'D36', 'D37', 'D38', 'D39', 'D40', 'D41', 'D42', 'D43', 'D44', 'D45', 'D46', 'D47', 'D48', 'D49', 'D50', 'D51', 'D52', 'D53', 'D54', 'D55', 'D56', 'D57', 'D58', 'D59', 'D60', 'D61', 'D62', 'D63', 'D64', 'D65', 'D66', 'D67', 'D68', 'D69', 'D70', 'D71', 'D72', 'D73', 'D74', 'D75', 'D76', 'D77', 'D78', 'D79', 'D80', 'D81', 'D82', 'D83', 'D85', 'D86', 'D87', 'D88', 'D89', 'D90', 'D91', 'D92', 'D93', 'D94', 'D95', 'D96', 'D97', 'D98', 'D99', 'DAA', 'DAD', 'DAY', 'DEC', 'DKW', 'DLT', 'DMK', 'DMO', 'DMQ', 'DMT', 'DPC', 'DPR', 'DPT', 'DRA', 'DRI', 'DRL', 'DRM', 'DTN', 'DWT', 'DZN', 'DZP', 'E01', 'E07', 'E08', 'E09', 'E10', 'E11', 'E12', 'E14', 'E15', 'E16', 'E17', 'E18', 'E19', 'E20', 'E21', 'E22', 'E23', 'E25', 'E27', 'E28', 'E30', 'E31', 'E32', 'E33', 'E34', 'E35', 'E36', 'E37', 'E38', 'E39', 'E40', 'E41', 'E42', 'E43', 'E44', 'FAH', 'FAR', 'FBM', 'FOT', 'FTK', 'FTQ', 'GBQ', 'GDW', 'GFI', 'GGR', 'GIA', 'GIC', 'GII', 'GIP', 'GLD', 'GLI', 'GLL', 'GRM', 'GRN', 'GRO', 'GRT', 'GWH', 'HAR', 'HBA', 'HBX', 'HDW', 'HGM', 'HIU', 'HKM', 'HLT', 'HMQ', 'HMT', 'HPA', 'HTZ', 'HUR', 'INH', 'INK', 'INQ', 'ISD', 'JOU', 'JPS', 'JWL', 'KBA', 'KCC', 'KEL', 'KGM', 'KGS', 'KHY', 'KHZ', 'KIC', 'KIP', 'KJO', 'KLK', 'KMA', 'KMH', 'KMK', 'KMQ', 'KMT', 'KNI', 'KNS', 'KNT', 'KPA', 'KPH', 'KPO', 'KPP', 'KSD', 'KSH', 'KTM', 'KTN', 'KUR', 'KVA', 'KVR', 'KVT', 'KWH', 'KWO', 'KWT', 'LAC', 'LBR', 'LBT', 'LEF', 'LPA', 'LTN', 'LTR', 'LUB', 'LUM', 'LUX', 'MAH', 'MAL', 'MAM', 'MAR', 'MAW', 'MBE', 'MBF', 'MBR', 'MCU', 'MGM', 'MHZ', 'MIK', 'MIL', 'MIN', 'MIO', 'MIU', 'MLD', 'MLT', 'MMK', 'MMQ', 'MMT', 'MND', 'MON', 'MPA', 'MQH', 'MQS', 'MSK', 'MTK', 'MTQ', 'MTR', 'MTS', 'MVA', 'MWH', 'NAR', 'NBB', 'NCL', 'NEW', 'NIU', 'NMI', 'NMP', 'NPL', 'NPR', 'NPT', 'NRL', 'NTT', 'ODE', 'OHM', 'ONZ', 'OZA', 'OZI', 'PAL', 'PFL', 'PGL', 'PLA', 'PTD', 'PTI', 'PTL', 'QAN', 'QTD', 'QTI', 'QTL', 'QTR', 'RPM', 'RPS', 'SAN', 'SCO', 'SCR', 'SEC', 'SET', 'SHT', 'SIE', 'SMI', 'SQR', 'SST', 'STI', 'STK', 'STL', 'STN', 'TAH', 'TIC', 'TIP', 'TMS', 'TNE', 'TPR', 'TQD', 'TRL', 'TSD', 'TSH', 'VLT', 'WCD', 'WEB', 'WEE', 'WHR', 'WSD', 'WTT', 'YDK', 'YDQ', 'YRD', '11_1', '13_1', '14_1', '15_1', '16_1', '17_1', '18_1', '19_1', '20_1', '21_1', 'DD_1', 'GT_1', 'IU_1', 'NT_1', 'PK_1', 'S3_1', 'S4_1', 'WE_1', 'B13_1', 'B35_1', 'C10_1', 'C62_1', 'C62_2', 'C93_1', 'DTN_1', 'DTN_2', 'INQ_1', 'LBR_1', 'MLD_1', 'MTQ_1', 'PLA_1', 'STN_1', 'TNE_1', 'BIL_US', 'BIL_EUR'] as const);

// Tipo derivado a partir del enum
export type UnidadDeMedida = z.infer<typeof unidadDeMedidaEnum>;

// Mapa clave -> descripción (algunas claves pueden tener más de una descripción)
export const unidadDeMedidaDescripcion: Record<UnidadDeMedida, string | string[]> = {
  '05': "lift",
  '06': "small spray",
  '08': "heat lot",
  '1A': "car mile",
  '1B': "car count",
  '1C': "locomotive count",
  '1D': "caboose count",
  '1E': "empy car",
  '1F': "train mile",
  '1G': "fuel usage gallon (US)",
  '1H': "caboose mile",
  '1I': "fixed rate",
  '1J': "ton mile",
  '1K': "locomotive mile",
  '1L': "total car count",
  '1M': "total car mile",
  '1X': "quarter mile",
  '22': "decilitre per gram",
  '23': "gram per cubic centimetre",
  '24': "theoretical pound",
  '25': "gram per square centimetre",
  '26': "acual ton",
  '27': "theoretical ton",
  '28': "kilogram per square metre",
  '29': "pund per thousand square feet",
  '2A': "radian per second",
  '2B': "radian per second squared",
  '2C': "roentgen",
  '2I': "British thermal unit per hour",
  '2J': "cubic centimetre per second",
  '2K': "cubic foot per hour",
  '2L': "cubic foot per minute",
  '2M': "centimetre per second",
  '2N': "decibel",
  '2P': "kilobyte",
  '2Q': "kilobecquerel",
  '2R': "kilocurie",
  '2U': "megagram",
  '2V': "megagram per hour",
  '2W': "bin",
  '2X': "metre per minute",
  '2Y': "milliröntgen",
  '2Z': "millivolt",
  '30': "horse power dar per air dry metric ton",
  '31': "catch weight",
  '32': "kilogram per air dry metric ton",
  '33': "kilopascal square metres per gram",
  '34': "kilopascals per millimetre",
  '35': "millilitres per square centimetre second",
  '36': "cubic feet per minute per square foot",
  '37': "ounce per square foot",
  '38': "ounces per square foot per 0,01 inch",
  '3B': "megajoule",
  '3C': "manmonth",
  '3E': "pund per pund of product",
  '3G': "pound per piece of product",
  '3H': "kilogram per kilogram of product",
  '3I': "kilogram per piece of product",
  '40': "millilitre per second",
  '41': "millilitre per minute",
  '43': "super bulk bag",
  '44': "fivehundred kg bulk bag",
  '45': "threehundred kg bulk bag",
  '46': "fifty lb bulk bag",
  '47': "fifty lb bag",
  '48': "bulk car load",
  '4A': "bobbin",
  '4B': "cap",
  '4C': "centistokes",
  '4E': "twenty pack",
  '4G': "microlitre",
  '4H': "micrometre (micron)",
  '4K': "milliampere",
  '4L': "megabyte",
  '4M': "milligram per hour",
  '4N': "megabecquerel",
  '4O': "microfarad",
  '4P': "newton per metre",
  '4Q': "ounce inche",
  '4R': "ounce foot",
  '4T': "picofarad",
  '4U': "pund per hour",
  '4W': "ton (US) per hour",
  '4X': "kilolitre per hour",
  '53': "theoretical kilograms",
  '54': "theoretical tonne",
  '56': "sitas",
  '57': "mesh",
  '58': "net kilogram",
  '59': "part per million",
  '5A': "barrel (US) per minute",
  '5B': "batch",
  '5C': "gallon (US) per thousand",
  '5E': "MMSCF/day",
  '5F': "pounds per thousand",
  '5G': "pump",
  '5H': "stage",
  '5I': "standard cubic foot",
  '5J': "hydraulic horse power",
  '5K': "count per minute",
  '5P': "seismic level",
  '5Q': "seismic line",
  '60': "percen weight",
  '61': "part per billion (US)",
  '62': "percent per 1000 hour",
  '63': "failure rate in time",
  '64': "pound per square inch, gauge",
  '66': "oersted",
  '69': "test specific scale",
  '71': "volt ampere per pund",
  '72': "watt per pound",
  '73': "ampere tum per centimetre",
  '74': "millipascal",
  '76': "gauss",
  '77': "milli-inch",
  '78': "kilogauss",
  '80': "pounds per sauqre inche absoulte",
  '81': "henry",
  '84': "kilopound per square inch",
  '85': "foot pound-force",
  '87': "pound per cubic foot",
  '89': "poise",
  '90': "saybold universal second",
  '91': "stokes",
  '92': "calorie per cubic centimetre",
  '93': "calorie per gram",
  '94': "curl unit",
  '95': "twenty thousand gallon (US) tankcar",
  '96': "ten thousand gallon (US) tankcar",
  '97': "ten kg drum",
  '98': "fifteen kg drum",
  'A1': "15° C Calorie",
  'A2': "ampere per centimetre",
  'A3': "ampere per millimetre",
  'A4': "ampere per squre centrimetre",
  'A5': "ampere square metre",
  'A6': "ampere per square metre kelvin squared",
  'A7': "ampere per square millimetre",
  'A8': "ampere second",
  'A9': "rate",
  'AA': "ball",
  'AB': "bulk pack",
  'AD': "byte",
  'AE': "ampere per metre",
  'AH': "additional minute",
  'AI': "average minute per call",
  'AJ': "cop",
  'AK': "fathom",
  'AL': "access line",
  'AM': "ampoule",
  'AP': "aluminum pound only",
  'AQ': "anti-hemophilic factor (AHF) unit",
  'AR': "suppository",
  'AS': "assortment",
  'AV': "capsule",
  'AW': "powder filled vial",
  'AY': "assembly",
  'AZ': "Brithis thermal unit per pound",
  'B0': "Btu per cubic foot",
  'B1': "barrel (US) per day",
  'B2': "bunk",
  'B3': "battin pound",
  'B4': "barrel,imperial",
  'B5': "billet",
  'B6': "bunk",
  'B7': "cycle",
  'B8': "joule per cubic metre",
  'B9': "battin pound",
  'BB': "base box",
  'BD': "board",
  'BE': "bundle",
  'BG': "bag",
  'BH': "brush",
  'BJ': "bucket",
  'BK': "basket",
  'BL': "bale",
  'BO': "bottle",
  'BP': "hundred board feet",
  'BR': "bar [unit of packaging]",
  'BT': "bolt",
  'BW': "base weight",
  'BX': "box",
  'BZ': "million BTUs",
  'C0': "call",
  'C1': "composite product pound (total weight)",
  'C2': "carset",
  'C3': "microvolt per metre",
  'C4': "carload",
  'C5': "cost",
  'C6': "cell",
  'C7': "centipoise",
  'C8': "millicoulomb per kilogram",
  'C9': "coil group",
  'CA': "can",
  'CG': "card",
  'CH': "container",
  'CJ': "cone",
  'CK': "connector",
  'CL': "coil",
  'CO': "carboy",
  'CQ': "cartridge",
  'CR': "crate",
  'CS': "case",
  'CT': "carton",
  'CU': "cup",
  'CV': "cover",
  'CY': "cylinder",
  'CZ': "combo",
  'D1': "reciprocal second per steradian",
  'D2': "reciprocal second per steradian metre squared",
  'D5': "kilogram per square centimetre",
  'D6': "roentgen per second",
  'D7': "sandwich",
  'D8': "draize score",
  'D9': "dyne per square centimetre",
  'DB': "dry pound",
  'DC': "disk (disc)",
  'DD': "degree Celsius hundred",
  'DE': "deal",
  'DG': "decigram",
  'DI': "dispense",
  'DJ': "decagram",
  'DN': "decinewton metre",
  'DQ': "data record",
  'DR': "drum",
  'DS': "display",
  'DT': "dry ton",
  'DU': "dyne",
  'DX': "dyne per centimetre",
  'DY': "directory book",
  'E2': "belt",
  'E3': "trailer",
  'E4': "gross kilogram",
  'E5': "metric long ton",
  'EA': "each",
  'EB': "electronica mail box",
  'EC': "each per month",
  'EP': "eleven pack",
  'EQ': "equivalen gallon",
  'EV': "envelope",
  'F1': "thousand cubic feet per day",
  'F9': "fibre per cubic centimetre of air",
  'FB': "field",
  'FC': "thousand cubic feet",
  'FD': "million particle per cubic foot",
  'FE': "track foot",
  'FF': "hundred cubic metre",
  'FG': "transdermal patch",
  'FH': "micromole",
  'FL': "flake ton",
  'FM': "million cubic feet",
  'FP': "pound per square foot",
  'FR': "foot per minute",
  'FS': "foot per second squared",
  'G2': "US gallon per minute",
  'G3': "Imperial gallon per minute",
  'G7': "microfiche sheet",
  'GB': "gallon (US) per day",
  'GC': "gram per 100 gram",
  'GD': "gross barrel",
  'GE': "pound per gallon (US)",
  'GF': "gram per metre (gram per 100 centimetres",
  'GH': "half gallon",
  'GJ': "gram per millilitre",
  'GK': "gram per kilogram",
  'GL': "gram per litre",
  'GM': "gram per square metre",
  'GN': "gross gallon",
  'GO': "milligrams per square metre",
  'GP': "milligrams per cubic metre",
  'GQ': "microgram per cubic metre",
  'GT': "gross ton",
  'GV': "gigajoule",
  'GW': "gallon per thousand cubic feet",
  'GY': "gross yard",
  'GZ': "gage-system",
  'H1': "half page- electronic",
  'H2': "half litr",
  'HA': "hank",
  'HC': "hundred count",
  'HD': "half dozen",
  'HE': "hundredth of a carat",
  'HF': "hundred feet",
  'HH': "hundred cubic feet",
  'HI': "hundred sheet",
  'HJ': "metric horse power",
  'HK': "hundred kilogram, dry wieight",
  'HL': "hundred feet (linear)",
  'HM': "mile per hour",
  'HN': "conventional millimetre of mercury",
  'HO': "hundred troy ounce",
  'HP': "conventional millimetre of water",
  'HS': "hundred square feet",
  'HT': "half hour",
  'HY': "hundred yard",
  'IA': "inche pound (pound inch)",
  'IC': "count per inche",
  'IE': "person",
  'IF': "inches of water",
  'II': "column inch",
  'IL': "inche per minute",
  'IM': "impression inch",
  'IP': "insurance policy",
  'IT': "count per centimetre",
  'IU': "inche per second",
  'IV': ["inch per second squared", "inch per second squared (acceleration)"],
  'J2': "joule per kilogram",
  'JB': "jumbo",
  'JE': "joule per kelvin",
  'JG': "jug",
  'JK': "megajoule per kilogram",
  'JM': "megajoule per cubic metre",
  'JO': "joint",
  'JR': "jar",
  'K1': "kilowatt demand",
  'K2': "kilovolt ampere reactive demand",
  'K3': "kilovolt ampere reactive hour",
  'K5': "kilovolt ampere (reactive)",
  'K6': "kilolitre",
  'KA': "cake",
  'KB': "kilocharacter",
  'KD': "kilogram decimal",
  'KF': "kilopacket",
  'KG': "keg",
  'KI': "kilogram per millimetre widht",
  'KJ': "kilosegment",
  'KL': "kilogram per metre",
  'KO': "milliequivalence caustic potash per gram of product",
  'KR': "kiloroentgen",
  'KS': "thousand pound per square inch",
  'KT': "kit",
  'KW': "kilograms per millimetre",
  'KX': "millilitre per kilogram",
  'L2': "litre per minute",
  'LA': "pound per cubic inch",
  'LC': "linear centimetre",
  'LD': "litre per day",
  'LE': "lite",
  'LF': "linear foot",
  'LH': "labour hour",
  'LI': "linear inch",
  'LJ': "large spray",
  'LK': "link",
  'LM': "linear metre",
  'LN': "length",
  'LO': "lot [unit of procurement]",
  'LP': "liquid pound",
  'LR': "layer",
  'LS': "lump sum",
  'LX': "linear yard per pound",
  'LY': "linar yard",
  'M1': "milligram per litre",
  'M4': "monetary value",
  'M5': "microcurie",
  'M7': "micro-inch",
  'M9': "million Btu per 1000 cubic feet",
  'MA': "machine per unit",
  'MC': "microgram",
  'MD': "air dry metric tone",
  'MF': "milligram per square foot per side",
  'MK': "milligram per square inch",
  'MO': "magnetic tape",
  'MQ': "thousand metre",
  'MT': "mat",
  'MV': "number of mults",
  'N1': "pen calorie",
  'N2': "number of lines",
  'N3': "print point",
  'NA': "milligram per kilogram",
  'NB': "barge",
  'NC': "car",
  'ND': "net barrel",
  'NE': "net litre",
  'NF': "message",
  'NG': "net gallon (US)",
  'NH': "message hour",
  'NI': "net imperial gallon",
  'NJ': "number of screens",
  'NL': "load",
  'NN': "train",
  'NQ': "mho",
  'NR': "micromho",
  'NT': "metric net ton",
  'NV': "vehicle",
  'NX': "part per thousand",
  'NY': "pound per air dry metric ton",
  'OA': "panel",
  'ON': "ounce per square yard",
  'OP': "two pack",
  'OT': "overtime hour",
  'OZ': "ounce av",
  'P0': "page -electronic",
  'P1': "percent",
  'P2': "pound per foot",
  'P3': "three pack",
  'P4': "four pack",
  'P5': "five pack",
  'P6': "six pack",
  'P7': "seven pack",
  'P8': "eight pack",
  'P9': "nine pack",
  'PA': "packet",
  'PB': "pair inch",
  'PD': "pad",
  'PE': "pound equivalent",
  'PF': "pallet (lift)",
  'PG': "plate",
  'PI': "pitch",
  'PK': "pack",
  'PM': "pound percentage",
  'PN': "pound net",
  'PO': "pound per inch of lengtt",
  'PQ': "page per inch",
  'PR': "pair inch",
  'PS': "pound-force per square inch",
  'PT': "pint (US)",
  'PU': "tray/tray pack",
  'PV': "half pint (US)",
  'PW': "pound per inch of width",
  'PY': "peck dry (US)",
  'PZ': "peck dry (UK)",
  'Q3': "meal",
  'QA': "page-facsimile",
  'QB': "page-hardcopy",
  'QD': "quarter dozen",
  'QH': "quarter hour",
  'QK': "quartes kilogram",
  'QR': "quire",
  'QT': "quart (US)",
  'R1': "pica",
  'R4': "calorie",
  'R9': "thousand cubic metre",
  'RA': "rack",
  'RD': "rod",
  'RG': "ring",
  'RH': "running or operating hour",
  'RK': "roll metric measure",
  'RL': "reel",
  'RM': "ream",
  'RN': "ream metric measure",
  'RO': "roll metric measure",
  'RP': "pound per team",
  'RS': "reset",
  'RT': "revenue ton mile",
  'RU': "run",
  'S3': "foot wquare per second",
  'S4': "metre squared per second (square metres/seconds US)",
  'S5': "sixty fourths of an inch",
  'S6': "session",
  'S7': "storage unit",
  'S8': "standard advertising unit",
  'SA': "sack",
  'SD': "solid pound",
  'SE': "section",
  'SG': "segment",
  'SK': "split tank truck",
  'SL': "slipsheet",
  'SN': "square rod",
  'SO': "spool",
  'SP': "shelf package",
  'SQ': "square",
  'SR': "strip",
  'SS': "sheet metric measure",
  'ST': "sheet",
  'SV': "skid",
  'SW': "skein",
  'SX': "shipment",
  'T0': "telecommunication line service",
  'T1': "thousand pound gross",
  'T3': "thousand piece",
  'T4': "thousand bag",
  'T5': "thousand casing",
  'T6': "thousand gallon (US)",
  'T7': "thousand impression",
  'T8': "thousand linear inch",
  'TA': "tenth cubic foot",
  'TC': "truckload",
  'TD': "therm",
  'TE': "tote",
  'TF': "ten square yard",
  'TI': "thousand square inch",
  'TJ': "thousand square centimetre",
  'TK': "tank, rectangular",
  'TL': "thousand feet (linear)",
  'TN': "tin",
  'TP': "ten pack",
  'TQ': "thousand feet",
  'TR': "ten square feet",
  'TS': "tonne of substance 90% dry",
  'TT': "thousand linear metre",
  'TU': "tube",
  'TV': "thousand kilogram",
  'TW': "thousand sheet",
  'TY': "tank, cylindrical",
  'U1': "tratment",
  'U2': "tablet",
  'UA': "torr",
  'UB': "telecommunication line in service average",
  'UC': "telecommunication port",
  'UD': "tenth minute",
  'UE': "tenth hour",
  'UF': "usage per telecommunication line average",
  'UH': "ten thousand yard",
  'UM': "million un it",
  'UN': "newton metre",
  'VA': "volt ampere per kilogram",
  'VI': "vial",
  'VQ': "bulk",
  'VS': "visit",
  'W2': "wet kilo",
  'W4': "two week",
  'WA': "watt per kilogram",
  'WB': "wet pound",
  'WE': "wet ton",
  'WG': "wine gallon",
  'WH': "wheel",
  'WI': "weight per square inch",
  'WM': "working month",
  'WW': "millilitre of water",
  'X1': "hchain",
  'YL': "hundred linear yard",
  'YT': "ten yard",
  'Z1': "lift van",
  'Z2': "chest",
  'Z3': "cask",
  'Z4': "hogshead",
  'Z5': "lug",
  'Z6': "conference point",
  'Z8': "newspage agate line",
  'ZP': "page",
  'ZZ': "muatually defined",
  'A10': "ampere square metre per joule second",
  'A11': "angstrom",
  'A12': "astronomical unit",
  'A13': "attojoule",
  'A14': "barn",
  'A15': "barn per electron volt",
  'A16': "barn per steradian electronvolt",
  'A17': "barn per steradian",
  'A18': "becquerel per kilogram",
  'A19': "becquerel per metre cubed",
  'A20': "British thermal unit per second square foot degree Rankin",
  'A21': "British thermal unit per pound degree Rankin",
  'A22': "British thermal unit per second foot degree Rankin",
  'A23': "Brithis thermal unit per hour square foot degree Rankin",
  'A24': "candela per square metre",
  'A25': "cheval vapeur",
  'A26': "coulomb metre",
  'A27': "coulomb metre squared per volt",
  'A28': "coulomb per cubic centimetre",
  'A29': "coulomb per cubic metre",
  'A30': "coulomb per cubic millimetre",
  'A31': "coulomb per kilogram second",
  'A32': "coulomb per mole",
  'A33': "coulomb per square centimetre",
  'A34': "coulomb per square metre",
  'A35': "coulomb per square millimetre",
  'A36': "cubic centimetre per mole",
  'A37': "cubic decimetre per mole",
  'A38': "cubic metre per coulomb",
  'A39': "cubic metre per kilogram",
  'A40': "cubic metre per mole",
  'A41': "ampere per square metre",
  'A42': "curie per kilogram",
  'A43': "deadweight tonnage",
  'A44': "decalitre",
  'A45': "decametre",
  'A47': "decitex",
  'A48': "degree Rankin",
  'A49': "denier",
  'A50': "dyne second per cubic centimetre",
  'A51': "dyne second per centimetre",
  'A52': "dyne second per centimetre to the fifth power",
  'A53': "electronvolt",
  'A54': "electronvolt per metre",
  'A55': "electronvolt square metre",
  'A56': "electronvolt square metre per kilogram",
  'A57': "erg",
  'A58': "erg per centimetre",
  'A59': "8-part cloud cover",
  'A60': "erg per cubic centimetre",
  'A61': "erg per gram",
  'A62': "erg per gram second",
  'A63': "erg per second",
  'A64': "erg per second square centimetre",
  'A65': "erg per square centimetre second",
  'A66': "erg square centimetre",
  'A67': "erg sqtuare centimetre per gram",
  'A68': "exajoule",
  'A69': "farad per metre",
  'A70': "femtojoule",
  'A71': "femtometre",
  'A73': "foot per second squared",
  'A74': "foot pound-force per second",
  'A75': "freight ton",
  'A76': "gallon (US) per thousand",
  'A77': "Gaussian CGS unit of displacement",
  'A78': "Gaussian CGS unit of electric current",
  'A79': "Gaussian CGS unit of electric charge",
  'A80': "Gaussian CGS unit of electric field strenght",
  'A81': "Gaussian CGS unit of electric polarization",
  'A82': "Gaussian CGS unit of electric potencial",
  'A83': "Gaussian CGS unit of magnetization",
  'A84': "gigacoulomb per cubic metre",
  'A85': "gigaelectronvolt",
  'A86': "gigahertz",
  'A87': "gigaohm",
  'A88': "gigaohm metre",
  'A89': "gigapascal",
  'A90': "gigawatt",
  'A91': "gon",
  'A92': "grade",
  'A93': "gram per cubic metre",
  'A94': "gram per mole",
  'A95': "gray",
  'A96': "gray per second",
  'A97': "hectopascal",
  'A98': "henry per metre",
  'A99': "bit",
  'ACR': "acre",
  'ACT': "activity",
  'AMH': "apere hour",
  'AMP': "ampere",
  'ANN': "year",
  'APZ': "troy ounce ot apothecary ounce",
  'ARE': "are",
  'ASM': "alcoholic strenght by mass",
  'ASU': "alcoholic strenght by volume",
  'ATM': "standard atmosphere",
  'ATT': "technical atmosphere",
  'B10': "bit per second",
  'B11': "joule per kilogram kelvin",
  'B12': "joule per metre",
  'B13': "joule per metre squared",
  'B14': "joule per metre to the fourth power",
  'B15': "joule per mole",
  'B16': "joule per mole kelvin",
  'B17': "credit",
  'B18': "joule second",
  'B19': "digit",
  'B20': "joule square metre per kilogram",
  'B21': "kelvin per watt",
  'B22': "kiloampere",
  'B23': "kiloampere per square metre",
  'B24': "kiloampere per metre",
  'B25': "kilobecquerel per kilogram",
  'B26': "kilocoulomb",
  'B27': "kilocoulomb per cubic metre",
  'B28': "kilocoulomb per square metre",
  'B29': "kiloelectronvolt",
  'B30': "gidibit",
  'B31': "kilogram metre per second",
  'B32': "kilogram metre squared",
  'B33': "kilogram metre squared per second",
  'B34': "kilogram per cubic decimetre",
  'B35': "kilogram per litre",
  'B36': "thermochemical calorie per gram",
  'B37': "kilogram-force",
  'B38': "kilogram-force metre",
  'B39': "kilogram-force metre per second",
  'B40': "kilogram-force per square metre",
  'B41': "kilojoule per kelvin",
  'B42': "kilojoule per kilogram",
  'B43': "kilojoule per kilogram kelvin",
  'B44': "kilojoule per mole",
  'B45': "kilomole",
  'B46': "kilomole per cubic metre",
  'B47': "kilonewton",
  'B48': "kilonewton metre",
  'B49': "kiloohm",
  'B50': "kiloohm metre",
  'B51': "kilopond",
  'B52': "kilosecond",
  'B53': "kilosiemens",
  'B54': "kilosiemens pe rmetre",
  'B55': "kilovolt per metre",
  'B56': "kiloweber per metre",
  'B57': "light year",
  'B58': "litre per mole",
  'B59': "lumen hour",
  'B60': "lumen per square metre",
  'B61': "lumen per watt",
  'B62': "lumen second",
  'B63': "lux hour",
  'B64': "lux second",
  'B65': "maxwell",
  'B66': "megaampere per square metre",
  'B67': "megabecquerel per kilogram",
  'B68': "gigabit",
  'B69': "megacoulomb per cubic metre",
  'B70': "megacoulomb per square metre",
  'B71': "megaelectronvolt",
  'B72': "megagram per cubic metre",
  'B73': "meganewton",
  'B74': "meganewton metre",
  'B75': "megaohm",
  'B76': "megaohm metre",
  'B77': "megasiemens per metre",
  'B78': "megavolt",
  'B79': "megavolt per metre",
  'B80': "gigabit per second",
  'B81': "reciprocal metre squared reciprocal second",
  'B82': "inche per linear foot",
  'B83': "metre to the fourth power",
  'B84': "microampere",
  'B85': "microbar",
  'B86': "microcoulomb",
  'B87': "microcoulomb per cubic metre",
  'B88': "microcoulomb per square metre",
  'B89': "microfarad per metre",
  'B90': "microhenry",
  'B91': "microhenry per metre",
  'B92': "micronewton",
  'B93': "micronewton metre",
  'B94': "miocroohm",
  'B95': "microohm metre",
  'B96': "micropascal",
  'B97': "microradian",
  'B98': "microsecond",
  'B99': "microsiemens",
  'BAR': "bar [unit of pressure]",
  'BFT': "board foot",
  'BHP': "brake horse power",
  'BLD': "dry barrel (S)",
  'BLL': "barrel (US)",
  'BQL': "becquerel",
  'BTU': "British thermal unit",
  'BUA': "bushel (US)",
  'BUI': "bushel (UK)",
  'C10': "millifarad",
  'C11': "milligal",
  'C12': "milligram per metre",
  'C13': "milligray",
  'C14': "millihenry",
  'C15': "millijoule",
  'C16': "millimetre per second",
  'C17': "millimetre squared per second",
  'C18': "millimole",
  'C19': "mole per kilogram",
  'C20': "millnewton",
  'C21': "kibibit",
  'C22': "millinewton per metre",
  'C23': "milliohm metre",
  'C24': "millipascal second",
  'C25': "milliradian",
  'C26': "millisecond",
  'C27': "millisiemens",
  'C28': "millisievert",
  'C29': "millitesla",
  'C31': "milliwatt",
  'C32': "milliwatt per square metre",
  'C33': "milliweber",
  'C34': "mole",
  'C35': "mole per cubic decimetre",
  'C36': "mole per cubic metre",
  'C37': "kilobit",
  'C38': "mole per litre",
  'C39': "nanoampere",
  'C40': "nanocoulomb",
  'C41': "nanofarad",
  'C42': "nanofarad per metre",
  'C43': "nanohenry",
  'C44': "nanohenry per metre",
  'C45': "nanometre",
  'C46': "nanoohm metre",
  'C47': "nanosecond",
  'C48': "nanotesla",
  'C49': "nanowatt",
  'C50': "neper",
  'C51': "neper per second",
  'C52': "picometre",
  'C53': "newton metre second",
  'C54': "newton metre squared kilogram squared",
  'C55': "newton per square metre",
  'C56': "newton per square millimetre",
  'C57': "newton second",
  'C58': "newton second per metre",
  'C59': "octave",
  'C60': "ohm centimetre",
  'C61': "ohm metre",
  'C62': "one",
  'C63': "parsec",
  'C64': "pascal per kelvin",
  'C65': "pascal per second",
  'C66': "pascal second per cubic metre",
  'C67': "pascal second per metre",
  'C68': "petajoule",
  'C69': "phon",
  'C70': "picoampere",
  'C71': "picocoulomb",
  'C72': "picofarad per metre",
  'C73': "picohenry",
  'C74': "kilobit per second",
  'C75': "picowatt",
  'C76': "picowatt per square metre",
  'C77': "pund page",
  'C78': "pund-force",
  'C79': "kilovolt ampere hour",
  'C80': "rad",
  'C81': "radian",
  'C82': "radian square metre per mole",
  'C83': "radian square metre per kilogram",
  'C84': "radian per metre",
  'C85': "reciprocal angstrom",
  'C86': "reciprocal cubic metre",
  'C87': "reciprocal cubic metre per second",
  'C88': "reciprocal electron volt per cubic metre",
  'C89': "reciprocal henry",
  'C90': "reciprocal joul eper cubic metre",
  'C91': "reciprocal kelvin or kelvin to the power minus one",
  'C92': "reciprocal metre",
  'C93': "reciprocal metre squared",
  'C94': "reciprocal minute",
  'C95': "reciprocal mole",
  'C96': "reciprocal pascal or pascal to the power minus one",
  'C97': "reciprocal second",
  'C98': "reciprocal second per cubic metre",
  'C99': "reciprocal second per metre squared",
  'CCT': "carrying capacity in metric ton",
  'CDL': "candela",
  'CEL': "degree Celsius",
  'CEN': "hundred",
  'CGM': "centigram",
  'CKG': "coulomb per kilogram",
  'CLF': "hundred leave",
  'CLT': "centilitre",
  'CMK': "square centimetre",
  'CMQ': "cubic centrimetre",
  'CMT': "centimetre",
  'CNP': "hundred pack",
  'CNT': "cental (UK)",
  'COU': "coulomb",
  'CTG': "content gram",
  'CTM': "metric carat",
  'CTN': "content ton (metric)",
  'CUR': "curie",
  'CWA': "hundred pounds (cwt)/hundred weight (US)",
  'CWI': "hundred weight (UK)",
  'D03': "kilowatt hour per hour",
  'D04': "lot [unit of weight]",
  'D10': "siemens per metre",
  'D11': "mebibit",
  'D12': "siemens square metre per mole",
  'D13': "sievert",
  'D14': "thousand linear yard",
  'D15': "sone",
  'D16': "square centimetre per erg",
  'D17': "square centimetre per steradian erg",
  'D18': "metre kelvin",
  'D19': "square metre kelvin per watt",
  'D20': "square metre per joule",
  'D21': "square metre per kilogram",
  'D22': "square metre per mole",
  'D23': "pen gram (protein)",
  'D24': "square metre per steradian",
  'D25': "square metre per steradian joule",
  'D26': "square metre per volt second",
  'D27': "steradian",
  'D28': "syphon",
  'D29': "terahertz",
  'D30': "terajoule",
  'D31': "terawatt",
  'D32': "terawatt hour",
  'D33': "tesla",
  'D34': "tex",
  'D35': "thermochemical calorie",
  'D36': "megabit",
  'D37': "thermochemical calorie per gram kelvin",
  'D38': "thermochemical calorie per second centimetre kelvin",
  'D39': "thermochemical calorie per second sqaure centimetre kelvin",
  'D40': "thousand litre",
  'D41': "tonne per cubic metre",
  'D42': "tropical year",
  'D43': "unified atomic mass unit",
  'D44': "var",
  'D45': "volt squared per kelvin squared",
  'D46': "volt-ampere",
  'D47': "volt per centimetre",
  'D48': "volt per kelvin",
  'D49': "milivolt per kelvin",
  'D50': "volt per metre",
  'D51': "volt per millimetre",
  'D52': "watt per kelvin",
  'D53': "wat per metre kelvin",
  'D54': "watt per square metre",
  'D55': "watt per square metre kelvin",
  'D56': "watt per square metre kelvin to the fourth power",
  'D57': "watt per steradian",
  'D58': "watt per steradian square metre",
  'D59': "weber per metre",
  'D60': "weber per millimetre",
  'D61': "minute [unit of angle]",
  'D62': "second [unit of angle]",
  'D63': "book",
  'D64': "block",
  'D65': "round",
  'D66': "cassette",
  'D67': "dollar per hour",
  'D68': "number of words",
  'D69': "inch to the fourth power",
  'D70': "International Table (IT) calorie)",
  'D71': "International Table (IT) calorie per second centimetre kelvin",
  'D72': "International Table (IT) calorie per second square centimetre kelvin",
  'D73': "joule square metre per kilogram",
  'D74': "kilogram per mole",
  'D75': "International Table (IT) calorie per gram",
  'D76': "International Table (IT) calorie per gram kelvin",
  'D77': "megacoulomb",
  'D78': "megajoule per second",
  'D79': "beam",
  'D80': "microwatt",
  'D81': "microtesla",
  'D82': "microvolt per metre",
  'D83': "millinewton metre",
  'D85': "microwatt per square metre",
  'D86': "millicoulomb per kilogram",
  'D87': "millimole per kilogram",
  'D88': "millicoulomb per cubic metre",
  'D89': "millicoulomb per square metre",
  'D90': "cubic metre (net",
  'D91': "rem",
  'D92': "band",
  'D93': "second per cubic metre",
  'D94': "second per radian cubic metre",
  'D95': "joule per gram",
  'D96': "pound gross",
  'D97': "pallet/unit load",
  'D98': "mass pound",
  'D99': "sleeve",
  'DAA': "decare",
  'DAD': "ten day",
  'DAY': "day",
  'DEC': "decade",
  'DKW': "kilogram drained net weight",
  'DLT': "decilitre",
  'DMK': "square decimetre",
  'DMO': "standard kilolitre",
  'DMQ': "cubic decimetre per mole",
  'DMT': "decimetre",
  'DPC': "dozen piece",
  'DPR': "dozen pair",
  'DPT': "displacement tonnage",
  'DRA': "dram (US)",
  'DRI': "dram (UK)",
  'DRL': "dozen roll",
  'DRM': "drachm (UK)",
  'DTN': "centner, metric 100kg",
  'DWT': "pennyweight",
  'DZN': "dozen",
  'DZP': "dozen pack",
  'E01': "newton per square centimetre",
  'E07': "megawatt hour per hour",
  'E08': "megawatt per hertz",
  'E09': "milliampere hour",
  'E10': "degree days",
  'E11': "gigacalorie",
  'E12': "mille",
  'E14': "kilocalorie (IT)",
  'E15': "kilocalorie (TH) per hour",
  'E16': "million BTU (IT) per hour",
  'E17': "cubic foot per second",
  'E18': "tonne per hour",
  'E19': "ping",
  'E20': "megabit per second",
  'E21': "shares",
  'E22': "TEU",
  'E23': "tyre",
  'E25': "active unit",
  'E27': "dose",
  'E28': "air dry ton",
  'E30': "strand",
  'E31': "square metre per litre",
  'E32': "litre per hour",
  'E33': "foot per thousand",
  'E34': "gigabyte",
  'E35': "terabyte",
  'E36': "petabyte",
  'E37': "pixel",
  'E38': "megapixel",
  'E39': "dots per inch",
  'E40': "part per hundred thousand",
  'E41': "kilogram force per square millimetre",
  'E42': "kilogram force per square centimetre",
  'E43': "joule per square centimetre",
  'E44': "kilogram-force metre per square centimetre",
  'FAH': "degree Fahrenheit",
  'FAR': "farad",
  'FBM': "fibre metre",
  'FOT': "foot per thousand",
  'FTK': "square foot",
  'FTQ': "cubic foot",
  'GBQ': "gigabecquerel",
  'GDW': "gram, dry weight",
  'GFI': "gram of fissile isotope",
  'GGR': "great gross",
  'GIA': "gill",
  'GIC': "gram, including container",
  'GII': "gill (UK)",
  'GIP': "gram, including inner packaging",
  'GLD': "dry gallon (S)",
  'GLI': "gallon (UK)",
  'GLL': "gallon (US)",
  'GRM': "gram",
  'GRN': "grain",
  'GRO': "gross",
  'GRT': "gross register ton",
  'GWH': "gigawatt hour",
  'HAR': "hecare",
  'HBA': "hectobar",
  'HBX': "hundred boxes",
  'HDW': "hundred kilogram, dry wieight",
  'HGM': "hectogram",
  'HIU': "hundred international unit",
  'HKM': "hundred kilogram, net mass",
  'HLT': "hectolitre",
  'HMQ': "million cubic metre",
  'HMT': "hectometre",
  'HPA': "hectolitre of pure alcohol",
  'HTZ': "hertz",
  'HUR': "hour",
  'INH': "inch",
  'INK': "square inch",
  'INQ': "cubic inch",
  'ISD': "international sugar degree",
  'JOU': "joule",
  'JPS': "hundred metre",
  'JWL': "number of jewels",
  'KBA': "kilobar",
  'KCC': "kilogram of choline chloride",
  'KEL': "kelvin",
  'KGM': "kilogram",
  'KGS': "kilogram per second",
  'KHY': "kilogram of hydrogen peroxide",
  'KHZ': "kilohertz",
  'KIC': "kilogram, including container",
  'KIP': "kilogram, including inner packaging",
  'KJO': "kilojoule",
  'KLK': "lactic dry material percentage",
  'KMA': "kilogram of methylamine",
  'KMH': "kilometre per hour",
  'KMK': "square kilometre",
  'KMQ': "kilogram per cubic metre",
  'KMT': "kilometre per hour",
  'KNI': "kilogram of nitrogen",
  'KNS': "kilogram named substance",
  'KNT': "knot",
  'KPA': "kilopascal",
  'KPH': "kilogram of potassium hydroxide (caustic potash)",
  'KPO': "kilogram of potassium oxide",
  'KPP': "kilogram of phosphorus pentoxide (phosphoric anhydride)",
  'KSD': "kilogram of substance 90% dry",
  'KSH': "kilogram of sodium hydroxide (caustic soda)",
  'KTM': "kilometre per hour",
  'KTN': "kilotonne",
  'KUR': "kilogram of uranium",
  'KVA': "kilovolt-ampere",
  'KVR': "kilovar",
  'KVT': "kilovolt",
  'KWH': "kilowatt hour",
  'KWO': "kilogram of tungsten trioxide",
  'KWT': "kilowatt",
  'LAC': "lactose excess percentage",
  'LBR': "pound",
  'LBT': "troy pound (US)",
  'LEF': "leaf",
  'LPA': "litre of pure alcohol",
  'LTN': "ton (UK) or long ton (US)",
  'LTR': "litre",
  'LUB': "metric ton, lubricating oil",
  'LUM': "lumen",
  'LUX': "lux",
  'MAH': "megavolt ampere reactive hours",
  'MAL': "mega litre",
  'MAM': "megametre",
  'MAR': "mevavolt ampere reactive",
  'MAW': "megawatt",
  'MBE': "thousand standard brick equivalent",
  'MBF': "thousand board feet",
  'MBR': "millibar",
  'MCU': "millicurie",
  'MGM': "milligram",
  'MHZ': "megahertz",
  'MIK': "square mile",
  'MIL': "thousand",
  'MIN': "minute [unit of time]",
  'MIO': "million",
  'MIU': "million international unit",
  'MLD': "billion (US)",
  'MLT': "millilitre per kilogram",
  'MMK': "square millimetre",
  'MMQ': "cubic millimetre",
  'MMT': "millimetre",
  'MND': "kilogra, dry weight",
  'MON': "month",
  'MPA': "megapascal",
  'MQH': "cunic metre per hour",
  'MQS': "cubic metre per second",
  'MSK': "metre per second squared",
  'MTK': "square metre",
  'MTQ': "cubic metre",
  'MTR': "metre",
  'MTS': "metre per second",
  'MVA': "megavolt-ampere",
  'MWH': "megawatt hour (1000kW.h)",
  'NAR': "number of articles",
  'NBB': "number of bobbins",
  'NCL': "number of cells",
  'NEW': "newton per square centimetre",
  'NIU': "number of international units",
  'NMI': "nautical mile",
  'NMP': "number of packs",
  'NPL': "number of parcels",
  'NPR': "number of pairs",
  'NPT': "number of parts",
  'NRL': "number of rolls",
  'NTT': "net register ton",
  'ODE': "ozone depletion equivalent",
  'OHM': "ohm",
  'ONZ': "ounce per square yard",
  'OZA': "fluid ounce (US)",
  'OZI': "fluid ounce (UK)",
  'PAL': "pascal",
  'PFL': "proof litre",
  'PGL': "proof gallon",
  'PLA': "pail",
  'PTD': "dry pint(US)",
  'PTI': "pint (UK)",
  'PTL': "liquid pint (US)",
  'QAN': "quarter (of a year)",
  'QTD': "dry quart (US)",
  'QTI': "quart (UK)",
  'QTL': "liquid quart (US)",
  'QTR': "quarter (UK)",
  'RPM': "revolutions per minute",
  'RPS': "revolutions per second",
  'SAN': "half year (6 months)",
  'SCO': "score",
  'SCR': "scruple",
  'SEC': "second [unit of time]",
  'SET': "set",
  'SHT': "shipping ton",
  'SIE': "siemens",
  'SMI': "mile (statute mile)",
  'SQR': "square, roofing",
  'SST': "short standard (7200 matches)",
  'STI': "stone (UK)",
  'STK': "stick, cigarette",
  'STL': "standard litre",
  'STN': "net ton (2000 lb)",
  'TAH': "kiloampere hour (thousand ampere hour",
  'TIC': "metric ton, including container",
  'TIP': "metric ton, including inner packaging",
  'TMS': "kilogram of imported meta, less offal",
  'TNE': "metric ton",
  'TPR': "ten pair",
  'TQD': "thousand cubic metre per day",
  'TRL': "trillion (EUR)",
  'TSD': "thousand square feet",
  'TSH': "ton of steam per hour",
  'VLT': "volt",
  'WCD': "cord",
  'WEB': "weber",
  'WEE': "week",
  'WHR': "watt hour",
  'WSD': "standard",
  'WTT': "watt",
  'YDK': "squared yard",
  'YDQ': "cubic yard",
  'YRD': "yard",
  '11_1': "outfit",
  '13_1': "ration",
  '14_1': "shot",
  '15_1': "stick, military",
  '16_1': "hundred fifteen kg drum",
  '17_1': "hundred lb drum",
  '18_1': "fiftyfive gallon (US) drum",
  '19_1': "tank truck",
  '20_1': "twenty foot container",
  '21_1': "forty foot container",
  'DD_1': "degree [unit of angle]",
  'GT_1': "metric gross ton",
  'IU_1': "inch per second (vibration)",
  'NT_1': "net ton",
  'PK_1': "package",
  'S3_1': "square foot per second",
  'S4_1': "square metre per second sixty fourths of an inch",
  'WE_1': "wrap",
  'B13_1': "joule per square metre",
  'B35_1': "kilogram per litre of product",
  'C10_1': "millivolt per metre",
  'C62_1': "piece",
  'C62_2': "unit",
  'C93_1': "reciprocal squared metre",
  'DTN_1': "decitonne",
  'DTN_2': "quintal, metric 100kg",
  'INQ_1': "inch cubed",
  'LBR_1': "pound decimal",
  'MLD_1': "milliard",
  'MTQ_1': "metre cubed",
  'PLA_1': "degree Plato",
  'STN_1': "ton (US) or short ton (UK/US)",
  'TNE_1': "tonne (metric ton)",
  'BIL_US': "trillion (US)",
  'BIL_EUR': "billion (EUR)",
} as const;


