import { z } from "zod"

export const rrnaSchema = z.object({
  regulation_number: z
    .string()
    .describe(
      "The unique identification number for the regulation or restriction."
    )
    .optional(),
  validity_period: z
    .string()
    .describe(
      "The validity period or expiration date for the regulation or restriction."
    )
    .optional(),
  producer_country_of_origin: z
    .string()
    .describe(
      "Information about the producer or country of origin, including the name of the producer and the country of origin, important with medicines. Always Name and Adress, country of origin."
    ),
  product_description: z
    .string()
    .describe(
      "Description of the product as mentioned in the regulation or restriction."
    ),
  quantity_to_withdraw_and_account: z
    .string()
    .describe(
      "The quantity to be withdrawn and accounted for. The quantity that it is authorized to be imported."
    ),
  authorized_customs_office: z
    .string()
    .describe("The customs office authorized for the transaction."),
  hs_code: z
    .string()
    .regex(new RegExp("^[0-9]{4}\\.[0-9]{2}\\.[0-9]{2}$"))
    .describe(
      "The Harmonized System (HS) code for the product classification."
    ),
  document_summary: z
    .string()
    .describe(
      "A detailed summary of this specific regulation or restriction document, including key regulatory details and context that can be useful for a human. This field is mandatory and must be generated by the LLM, it is not provided in the document."
    )
})